[package]
name = "process-utils"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[dependencies]
tokio = { workspace = true, optional = true, features = ["process"] }

[features]
default = ["tokio"]
tokio = ["dep:tokio"]
