[package]
name = "amf0"
version = "0.2.0"
edition = "2024"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(coverage_nightly)'] }

[dependencies]
byteorder = { workspace = true }
thiserror = { workspace = true }
